'''BMI'''
def main():
    '''asdf'''
    per1 = input()
    wei1 = float(input())
    tal1 = float(input())
    per2 = input()
    wei2 = float(input())
    tal2 = float(input())
    per3 = input()
    wei3 = float(input())
    tal3 = float(input())
    per4 = input()
    wei4 = float(input())
    tal4 = float(input())
    per5 = input()
    wei5 = float(input())
    tal5 = float(input())
    print("%s's  BMI = %.2f" %(per1, (wei1/(tal1/100)**2)))
    print("%s's  BMI = %.2f" %(per2, (wei2/(tal2/100)**2)))
    print("%s's  BMI = %.2f" %(per3, (wei3/(tal3/100)**2)))
    print("%s's  BMI = %.2f" %(per4, (wei4/(tal4/100)**2)))
    print("%s's  BMI = %.2f" %(per5, (wei5/(tal5/100)**2)))
main()
